### ISSUE TITLE
Change default reward timing and delete red flash

### ISSUE THREAD

**Issue by KBMD** [jonkb/TicTrainer-node#14]
1. Change starting tic-free reward duration from 1 to 3 seconds. Ideally, make this an admin setting.
2. Change default time to increase reward to 5 consecutive rewards. Ditto admin.
3. Take away the red flash on the user page when a tic is observed (if possible make it an optional admin setting).

**Comment by jonkb** [comment]
Should these be system-wide settings or per-user settings? I could do it either way.

**Comment by KBMD** [comment]
I suppose per-user, but the default should be this way
Dad

Kevin J. Black

**Comment by KBMD** [comment]
Done
