### ISSUE TITLE
Add visual and/or auditory "coins"

### ISSUE THREAD

**Issue by KBMD** [jonkb/TicTrainer-node#17]
Ring a bell for each point delivered. And/or show a coin for each point. Possibly a Unicode coin-like symbol (smiley face?) printed to a text box?
  Rationale: The TicTimer setup that partly inspired TicTrainer delivers a plastic token for each defined tic-free interval, with a noise.

**Comment by jonkb** [comment]
This is the most important feature to add first.

**Comment by jonkb** [comment]
Clarification: this kind of session, if programmed in TicTrainer, does not need to use any other features of TicTimer. Specifically it has to reset rewards to zero for each session, "coins" doesn't mean the same thing as in the current TicTrainer user/trainer thing, etc.

**Comment by jonkb** [comment]
Done. I made a coin.svg and used a small bell audio clip.
Though this is only running in the nt sessions. I could add the audio to the TicTrainer sessions too if we want that.
