### ISSUE TITLE
Create separate DRZ user-session page

### ISSUE THREAD

**Issue by jonkoller** [jonkb/TicTrainer-node#20]
* copy session/session-user.dynh to new session-user-drz.dynh
* In ret_dynamic.ret_session_user, add DRZ check and request drz page
* Add a new case in the server.js request handler thingie; either copy the session-user case, or let it fall through to the session-user and change what needs changing.

**Comment by jonkb** [comment]
Replace the points and rate counters that are there now with something to represent the token dispenser. (visual "token" and sound)
Replace the current loglpc function with something that writes a line to the log file when a 10s interval is completed and when a reward is delivered (for DRZ, those are at the same time), just like it is in the TicTimer program (see [an example log file from TicTimer](https://github.com/jonkb/TicTimer/blob/master/data_reader/1234_session3_DRZ_TicTimer_log_example.txt) if that's helpful).

**Comment by jonkb** [comment]
Done. NCR is not done yet, but it can be implemented in the same page (nt/session-ntuser.dynh).
