### ISSUE TITLE
new labels for NewTics ratings user screen

### ISSUE THREAD

**Issue by KBMD** [jonkb/TicTrainer-node#24]
1. On the screeen the user sees during a DRZ session, it currently says "Reward Tokens:" at the top of the window, above where the tokens appear. So far so good. But for Baseline or Verbal sessions, that heading also appears even though there are no tokens. So first, please remove "Reward Tokens:" from the screen for Baseline and Verbal sessions but keep it for DRZ and NCR conditions.
2. I've thought for awhile that we should do the following. Above the "Reward Tokens:" message, please add "OK to tic" (larger font and/or bold face, optionally with a light green background on that message) for the Baseline session. For all other sessions, please instead add above the "Reward Tokens:" message the phrase "Don't tic" (same font & face as "OK to tic", but optionally with a light red background on that message).

**Comment by jonkb** [comment]
Done. The background color is now an option in the new options file: /scripts/settings.json
