### ISSUE TITLE
in tsp mode, file saves with e.g. "a-u5" not "a2-u5" ...

### ISSUE THREAD

**Issue by KBMD** [jonkb/TicTrainer-node#35]
... and there's nothing in the file to show which admin / rater was doing the ratings. I think that's important.

**Comment by jonkb** [comment]
Ok yeah, it shouldn't be too hard to put rater id into the log file.
The reason it's being done like that is that the user doesn't know which admin it's trying to connect to. Usually, both trainer and user specify which account they're trying to link to, but with tsp sessions it's not symmetrical like that.

**Comment by KBMD** [comment]
Ok but I'd like the log files to show which "a" did that session. The user
doesn't see the log files directly, correct?


Kevin J. Black

**Comment by jonkb** [comment]
Ok, I just made that change and pushed it to the master branch.
